### ISSUE TITLE
Maintain correct project structure

### ISSUE THREAD

**Issue by Sunnepah** [TiinaVask/Class1#1]
You should have a specific folder for the current project, for example, all the files for your lab today on PHP should be inside the folder __**mywebapp**__

**Comment by TiinaVask** [comment]
Thank you. Is it ok now?

**Comment by Sunnepah** [comment]
@TiinaVask, it's fine now.

**Comment by TiinaVask** [comment]
Hi. I have posted all works except for following homeworks (I dont know yet how to do them): 
HOMEWORK nr 1: 
http://www.free-css.com/free-css-templates/page196/conquer 
Tasks for Class Work
1. `When I hover on the navigation bar of your webpage, I want the hover effect to make the box white and the text inside the box Black`
2. `When I click the send button in the contact form I want to see all the information entered into the box popped up in an alert box`
3. `If any field is missing/empty when user clicks submit button on contact form, pop up and alert box saying the name of the missing field/fields`
Extra tasks for Home Work
4. `On click of the green button, change the text of the button to a different text and the color of the button to a different colour` .
5. `Link one of the div buttons to your public Facebook or Github profile (feel free to select any button you live"` (edited)
https://dev.to/sarah_chima/var-let-and-const--whats-the-difference-69e

**Comment by TiinaVask** [comment]
HOMEWORK nr 2: 

We have to create a currency conversion web-service (using jquery, API, fixer.io) etc. I still don't know how to do that. At first i need to prepare a form using html and javascript perhaps. Difficult. 
![image](https://user-images.githubusercontent.com/36072811/37868022-ad4b67ce-2f5d-11e8-9fa8-67524e463321.png)


These 2 works taked all time from beginners like me. And we did not find a solution. So we just wasted time. If you can help with these tasks, I would be very appreciated.
